name: Scrape KW SessionNet Termine

on:
  schedule:
    - cron: "17 5 * * *"   # 07:17 Berlin
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Debug tree
        run: |
          echo "Branch:" $(git rev-parse --abbrev-ref HEAD)
          find . -maxdepth 3 -type f | sort

      - name: Run scraper
        run: |
          python scripts/scrape_termine.py

      - name: Commit data if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/termine.json data/termine.ics || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(data): update termine (json+ics)"
            git push
          else
            echo "No changes."
          fi
